# Primitive Data Types, operators and expressions
*  data types: int, float, str, bool, None</b><br/>
*   Arithmetic operators: +, -, *,**, /, //, %</b><br/>
*  Logical operators: and, or, not </b><br/>
* Conditional operators: ==, !=, <, >, <=, >=
*  Abstract operators: [], \[::\], + </b><br/>
*  casting data types, int(), str(), float(), bool()
*  operations involving different data types,
*  Eg "123" + 456
*  Expressions are evaluated (calculated to give a value in one of the data types)

### Pre-lesson CheckPoint
1. Open your favourite IDE
2. Write Python Expressions with operators  which uses the foolwing data types
(each data type 1 expression each)
* int
* float
* str
* bool

<link rel="stylesheet" href="../custom.css">

# Programming Primitives(Statements), Assignments,  Function Calls
<ul>
<li> variables assignments</li>
<li> naming convention </i>
<li> swapping variables </li>
<li> statically typed vs dynamically typed languages
<li> calling a function </li>
<li> input, output </li>
<li> formatted printing </li>
</ul>

## Inputs Sources
* Web API
* Hardware Sensors
* User Input **
* File input **
* Sockets **

<link rel="stylesheet" href="../custom.css">

# Programming Construct :Selection (Conditional Branching)
<ul>
<li> Comparision operators: ==, !=, >,>=,<,<= </li>
<li> is, in </li>
<li> evaluates to a Boolean value</li>
<li> if .. elif .. else ..</li>
<li>Statements block
</ul>

In [ ]:
if <condition>:
    pass
    pass
elif <condition>:
    pass
    pass
else:
    pass

<link rel="stylesheet" href="../custom.css">

# Problem: Enter a mark and Convert marks to grade:
* \>= 70 -> A,
* 60-69 -> B,
* 55-59 -> C ,
* 50-54 -> D,
* <50 -> Fail

In [ ]:
## 24/2/2022
## Volunteer (Arishta) to paste your code here
raw = input('Please enter your marks here:') ## assume that a mark is an integer
if raw == "":
    print("Invalid input")
else:
    mark = int(raw)
    if mark >69:
        print('A')
    elif mark >59:
        print('B')
    elif mark >55:
        print('C')
    elif mark >49:
        print('D')
    else:
        print('Sorry man you failed :(')

<link rel="stylesheet" href="../custom.css">

# Data Validation vs Verification
*   Presence Check:
*   Range Check
*   Length Check
*   Format Check
___
*   Check Digits(Parity/Checksum), Example last letter on your NRIC
    -  Discuss later

In [ ]:
"12356".isnumeric(),"12356".isdigit(), "1236".isdecimal()

In [ ]:
i = "1234S"
int(i)
if i.isdigit():
    i = int(i)
type(i)

In [ ]:
# isnumeric(), isdigit, isdecimal()
# isnumeric()includes unicode numbers like 一二三,
# isdigit, includes superscript, subscript unicode codepoints like ²
# isdecimal(),includes fractions like  ½

# Test Cases:
#in_str = "123"
#in_str= "1.23" #is not a decimal
in_str = "\u4e09" #unicode chinese
#in_str=  '2\u00B2' # unicode superscript, is a digit/numeric, but not a decimal
#in_str = '4\u00BD' # Fraction


print(in_str, "\nisNumeric is", in_str.isnumeric(),
              "\nisDigit is", in_str.isdigit(),
              "\nisDecimal is",in_str.isdecimal()
     )
if in_str.isdecimal():
    print(int(in_str))

# What if mark is a float, Eg 45.5 ?
# Check for a floating point number ?

In [ ]:
## possible to use split ..let's see in later lesson
raw = input("float number")
left, right = raw.split(".")
print(left, right)

<link rel="stylesheet" href="../custom.css">

# Programming Construct: Iterations
Most loop requires the following :
* initialise the loop variable/s
* check terminating condition of loop variable
* update loop variable
```
    while <condition>:
      pass

    for loop_variable in range(start,stop,step) # start,start+step,..stop-1
      pass
```

In [ ]:
## Loop to print 1, 3, ..11
i=1
while i <= 12:
    print(i)
    i += 2

### Collection vs Iterable/Iterator
* elements in a collection can be access directly using an in index
* elements in a iterable/iterator has to be access sequentially using a for loop

In [ ]:
L = "Hello World" ## a str is a collection
It = iter("Hello World") ## Iterable will generate "H","e"..

## using a for loop

##Iterating through the elements in a collection vs iterating over the indices of the collection

# Problem 1: Extract digits from a number, 123 -> 3, 2, 1

In [ ]:
i = 1234
while i > 0:
    print(i%10)
    i = i//10

In [ ]:
ii = 12345
s = str(ii)
for i in s:
  print(i,end=' ')

In [ ]:

s = "abcdefg"
for j in range(len(s)-1,-1,-1):
    print(s[j])

# Problem 2 : Check if a number is prime

In [ ]:
## A prime number is divisible by 1 and itself
## Making use of solution in Problem 4

n = int(input("Enter a +ve number staring from 2 to chedck if it is prime"))
if len(find_factors(n)) == 2:
    print("Is a prime")
else:
    print("Not a prime")

# Problem 3 : convert marks to grade repeatedly

In [ ]:
# Ho Jia Le
while True:
    score = input('Please enter your marks here:')
    if score == "": ## check for both presence and termination condition
        break
    else:
        score = int(score)
        if score >69:
            print('A')
        elif score >59:
            print('B')
        elif score >55:
            print('C')
        elif score >49:
            print('D')
        else:
            print('Your grade is a fail.')

In [ ]:
# Using another approach, with try except:
score = input('Please enter your marks here:')
while score != "":
    try:
        score = int(score)
        if score >69:
            print('A')
        elif score >59:
            print('B')
        elif score >55:
            print('C')
        elif score >49:
            print('D')
        else:
            print('Your grade is a fail.')
    except:
        print("Invalid input")
    score = input('Please enter your marks here:')

In [ ]:
#Kavish
gradeArr = ["A", "B", "C", "D", "Fail"]
marksArr = [101, 70, 60, 55, 50, 0]

# Loops through the array and cross-references an index from the marksArr to gradeArr to get the grade
def grader():
    # Makes sure string inputs are caught before displaying any errors as we are using int() here
    try:
        mark = float(input("Input your marks\n"))
        for i in range(len(marksArr)):
            if (mark < marksArr[i] and mark >= marksArr[i + 1]):
                print(f'Your grade: {gradeArr[i]}')
        grader()
    except:
        return ## The issue here is that you can't ask the user to re-enter if there is an invalid input
               ## you have to catch specific

grader()

In [ ]:
#Kavish
# modified to recover from invalid input
gradeArr = ["A", "B", "C", "D", "Fail"]
marksArr = [101, 70, 60, 55, 50, 0]

# Loops through the array and cross-references an index from the marksArr to gradeArr to get the grade
def grader():
    # Makes sure string inputs are caught before displaying any errors as we are using int() here
    try:
        mark = input("Input your marks\n")
        mark = float(mark)
        for i in range(len(marksArr)):
            if (mark < marksArr[i] and mark >= marksArr[i + 1]):
                print(f'Your grade: {gradeArr[i]}')
        grader()
    except:
        if mark == "":
            return
        print("Invalid input")
        grader()

grader()

# Problem 4: find all the factors for a +ve integer n

In [ ]:
n = int(input("input a number"))
for i in range(1, n+1):
    if n % i == 0:
        print(i)

In [ ]:
## Show in class
#problem 4
# Naren
## Refactor as a function

def find_factors(integer_n):
  factors = []
  for i in range(1,integer_n+1) : ##
    if integer_n % i == 0:
        factors.append(i)
  return factors

In [ ]:
number = int(input())
for i in range(1, number + 1): print(i) if number % i == 0 else None


# Problem 5 Arithmetic Sequence

In mathematics, an **arithmetic sequence** is a sequence of real numbers
$$u_1,u_2,\cdots, u_n$$
such that the difference between two consecutive terms is constant, i.e. $u_{n+1}-u_n=d$ for some constant $d\in \mathbb{R}$, called the **common difference** and $n\geq 1$.

For example, the sequence $2,5,8,11,14,\dots$ is an arithmetic sequence with first term $2$ and common difference $3$.
>   a = 2, d = 3 find the nth term
>
>2, 5, 8, ... n<sup>th<sup>
>
> Term T<sub>n</sub> = a + (n-1)d

In [ ]:
n = 3
a = 2
d = 3
## sequence should be 2,5,8,11,...
print(f"The {n}th term is {a+(n-1)*d}") ## Math solution

In [ ]:
## Using a while loop
## Computing solution for seqeunces that do not have a math formula, Eg Collatz seqeunce ,sequence of prime numbers up to nth term
term = a
count= 1
while count < n:
    term = term + d
    count += 1
print(f"The {count}th term is {term}")

In [ ]:
## Using a for loop
term = a
for i in range(1,n):
    term = term + d
print(f"term {i+1} is {term}") ## Why Wrong?! Use a Trace Table

# Problem 6 (Ex 1.3) Find the nth term of a geometric sequence

## Geometric Series

In mathematics, a **geometric sequence** is a sequence of real numbers
$$u_1,u_2,\cdots, u_n$$
such that the ratio between two consecutive terms is constant, i.e. $\frac{u_{n+1}}{u_n}=r$ for some constant $r\in \mathbb{R}\backslash \{0,1\}$, called the **common ratio** and $n\geq 1$.

For example, the sequence $2,6,18,54,162,\dots$ is an arithmetic sequence with first term $2$ and common ratio $3$.

Write a program to generate the first $n$ terms of an arithmetic sequence with a user defined first term $a$ and common ratio $r$.

The problem:
- Request a numeric input from the user to be used as the first term.  Let us denote this input as `first_term`.
- Request a numeric input from the user to be used as the common difference.  Let us denote this input as `common_ratio`.
- Request an integer input from the user for the number of terms.  Let us denote this input as `number_of_terms`.
- Print out the sequence up to the nth term.

Example interaction:

>Please input the first term in the geometric sequence:<br>
>2<br>
>Please input the common ratio:<br>
>3<br>
>Please input the number of terms:<br>
>5<br>
>The first 5 terms of the geometric sequence are:<br>
>2<br>
>6<br>
>18<br>
>54<br>
>162<br>

In [ ]:
## Complete this as homework

## Compound Interest

Mr. $B$ was offered an investment opportunity with a company where if he was to invest \$1000, he was guaranteed a 100% yearly interest rate, i.e. Mr. $B$ will be receive \$2000 after 1 year, inclusive of his capital.  

A friend of his that work in the company offers him another deal: same capital \$1000, same yearly interest rate of 100% but applied quarterly for a year, meaning every 3 months, the applied interest rate to the current amount is $\frac{100}{4}\%=25\%$. So, after 3rd month, his investment becomes \$1250. After 6th month, it's \$1562.50. After 9th month, it's \$1953.13.
Under this scheme, how much would Mr. $B$'s investment worth after a full year?

Suppose that instead of applying the interest rate of 100% quarterly, a human error caused the interest rate to be applied *hourly* instead, for a full year. How much value will Mr. $B$'s investment worth then?

In [ ]:
## Complete this as homework
## Kavish
## the one-liner
print(1000 * ((100+(100/(365*24)))/100)**(365*24))

## the for loop
investment = 1000
for i in range(365*24):
  investment = investment * ((100+(100/(365*24)))/100)

print(f"{round(investment,2)}")

<link rel="stylesheet" href="../custom.css">

# Collection Types: String, List, Tuple
* Iterables
* index, zero-based
* slicing, [start:stop:step]
* for .. in iterable iterate through the elements in the collection
* for .. in range(len(L)) iterate through the indexes of the collection

<link rel="stylesheet" href="../custom.css">

# List methods
<ul>
<li> method(operation) vs function </li>
<li> creating list</li>
<li> .append(object) </li>
<li> .index(object) </li>
<li> .count(object)</li>
<li> .pop(index)</li>
<li> .remove(object)</li>
<li> .insert(index,object)</li>
<li> .sort() </li>

</ul>

In [ ]:
## Previously to model a student with name, age, IP
name = "John"
age = 17
IP = False
print ( f"{name} is {age:>03} years old and he is { '' if IP else 'not'} a IP student")

### Using a List that contans different data types

In [ ]:
nested_L = [1,3,5,"hello world",[ 11,13,17,[ 2,4,6,8,"3rd level end"],19,23, "2nd level end"],1.5,3.17,("abc","tuple end")," 1st level end" ]

### Using a List that stores the same data types
* Stores a list of marks for a quiz

### How to model a class of students with thier names, age, IP and marks ?

### Tuple
* Immutable
* usually used by a function to return multiple values, eg divmod(number, divisir)->(quotient, remainder)

## Exercise 3.1 Dude, What's my Index?

Consider the following list

`[3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 8, 9, 7, 9, 3, 2, 3, 8, 4, 6, 2, 6, 4, 3, 3, 8, 3, 2, 7, 9, 5, 0, 2, 8, 8]`

Write a program that print out:
- the indices of occurence of each digit (0-9) in the list, and
- its number of occurences in the list
in the following format.
> `<DIGIT> <LIST_OF_INDICES> <NO_OF_OCCURENCES>`<br>

Example Output:

> Digit 0 : \[32\] : 1

Try your program again with the following list.

`[3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 8, 9, 7, 9, 3, 2, 3, 8, 4, 6, 2, 6, 4, 3, 3, 8, 3, 2, 7, 9, 5, 2, 8, 8]`

In [ ]:
number_list = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 8, 9, 7, 9, 3, 2, 3, 8, 4, 6, 2, 6, 4, 3, 3, 8, 3, 2, 7, 9, 5, 0, 2, 8, 8]

In [ ]:
## Homework code
number_list = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 8, 9, 7, 9, 3, 2, 3, 8, 4, 6, 2, 6, 4, 3, 3, 8, 3, 2, 7, 9, 5, 0, 2, 8, 8]
positions = []
numpositions = []
for num in range(10):
    for i in range(len(number_list)):
        if number_list[i] == num:
            positions.append(i)
    numpositions.append(positions)
    positions = []
for i in range(10):
    print("Digit {} : {} : {}".format(i,numpositions[i],len(numpositions[i])))

<link rel="stylesheet" href="../custom.css">

# Dictionary
<ul>
<li> collection of key,value pairs</li>
</ul>

<link rel="stylesheet" href="../custom.css">

* String, List, Tuple, y are collections that allows direct access to each element using an index
* A Dictionry allow direct access to an element using a key
* use of .keys() , values(), items()

In [ ]:
## Previously to model a student with name, age, IP
name = "John"
age = 17
IP = False
print ( f"{name} is {age:>03} years old and he is { '' if IP else 'not'} a IP student")

### Using a dictionary to model a student

In [ ]:
student = {
    "name": "John",
    "age": 17,
    "IP" : False
}

### Using a dictionary to count

In [ ]:
from my_stuff import *
## I have a live car detection ADT named Car_Detector that can
## detect colours of car from a webcam and return the first n cars detected
colours_dict={}
for colour in Car_Detector(1000):
    if colour in colours_dict:
        colours_dict[colour] +=1
    else:
        colours_dict[colour] = 1 ## create a new key,value pair
print(colours_dict)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.bar(colours_dict.keys(), colours_dict.values(), 0.5)

### Complete Ex 3.1 again using dictionary

In [ ]:
## homework
number_list = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 8, 9, 7, 9, 3, 2, 3, 8, 4, 6, 2, 6, 4, 3, 3, 8, 3, 2, 7, 9, 5, 0, 2, 8, 8]
dict1 = {0:[],1:[],2:[],3:[],4:[],5:[],6:[],7:[],8:[],9:[]}
for i in range(len(number_list)):
    dict1[ number_list[i]].append(i)

tuples = dict1.items()

new_d = dict(tuples)
new_d

In [ ]:
### List Comprehension
import random
list1 = [ [] for i in range(10)]
list1 =[ random.randint(0, 9) for _ in range(10)]
list1

___

<link rel="stylesheet" href="..\custom.css">

# Decimal , Fractions, Integers

* Decimal : Base 10 System
* float:(Floating point format: IEEE 754) Real Numbers , numbers with a decimal point
* int: (2's complement format)

___

### Mutable vs Immutable Data types

In [ ]:
listA = [1,2]
listB = ["a","b"]
immutable = (listA, listB)
print(immutable[0], immutable[1])
immutable[0]="abc"

In [ ]:
tupleA =(1,2)
tupleB = ("a","b")
mutable = [tupleA, tupleB]
print(mutable[0], mutable[1])